"""day5 session lead state

Revision ID: 28bc1928a761
Revises: 7325a156b7b0
Create Date: 2026-08-27 16:19:39.815432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "28bc1928a761"
down_revision: Union[str, Sequence[str], None] = "7325a156b7b0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column(
        "chat_message",
        sa.Column("intent", sa.String(length=100), nullable=True),
    )
    op.add_column(
        "chat_message",
        sa.Column("state", sa.String(length=100), nullable=True),
    )
    op.create_index(
        op.f("ix_chat_message_session_id"),
        "chat_message",
        ["session_id"],
        unique=False,
    )

    op.add_column(
        "chat_session",
        sa.Column("session_token", sa.String(length=255), nullable=False),
    )
    op.add_column(
        "chat_session",
        sa.Column("last_activity_at", sa.DateTime(), nullable=False),
    )
    op.add_column(
        "chat_session",
        sa.Column("source_page", sa.String(length=1000), nullable=True),
    )
    op.add_column(
        "chat_session",
        sa.Column("status", sa.String(length=50), nullable=False),
    )
    op.create_index(
        op.f("ix_chat_session_session_token"),
        "chat_session",
        ["session_token"],
        unique=True,
    )

    op.create_unique_constraint(
        None,
        "knowledge_document",
        ["filename"],
    )

    op.add_column(
        "lead_submission",
        sa.Column("session_id", sa.Integer(), nullable=False),
    )
    op.add_column(
        "lead_submission",
        sa.Column("full_name", sa.String(length=255), nullable=False),
    )
    op.add_column(
        "lead_submission",
        sa.Column("contact_number", sa.String(length=100), nullable=False),
    )
    op.add_column(
        "lead_submission",
        sa.Column("company_name", sa.String(length=255), nullable=True),
    )
    op.add_column(
        "lead_submission",
        sa.Column("project_summary", sa.Text(), nullable=True),
    )
    op.add_column(
        "lead_submission",
        sa.Column("service_interest", sa.String(length=255), nullable=True),
    )
    op.add_column(
        "lead_submission",
        sa.Column("timeline", sa.String(length=255), nullable=True),
    )
    op.add_column(
        "lead_submission",
        sa.Column("budget_range", sa.String(length=255), nullable=True),
    )
    op.add_column(
        "lead_submission",
        sa.Column("source_page", sa.String(length=1000), nullable=True),
    )
    op.add_column(
        "lead_submission",
        sa.Column("conversation_summary", sa.Text(), nullable=True),
    )
    op.create_index(
        op.f("ix_lead_submission_session_id"),
        "lead_submission",
        ["session_id"],
        unique=True,
    )
    op.create_foreign_key(
        None,
        "lead_submission",
        "chat_session",
        ["session_id"],
        ["id"],
    )

    op.drop_column("lead_submission", "name")
    op.drop_column("lead_submission", "message")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column(
        "lead_submission",
        sa.Column(
            "message",
            sa.TEXT(),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "lead_submission",
        sa.Column(
            "name",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=False,
        ),
    )

    op.drop_constraint(
        None,
        "lead_submission",
        type_="foreignkey",
    )
    op.drop_index(
        op.f("ix_lead_submission_session_id"),
        table_name="lead_submission",
    )

    op.drop_column(
        "lead_submission",
        "conversation_summary",
    )
    op.drop_column(
        "lead_submission",
        "source_page",
    )
    op.drop_column(
        "lead_submission",
        "budget_range",
    )
    op.drop_column(
        "lead_submission",
        "timeline",
    )
    op.drop_column(
        "lead_submission",
        "service_interest",
    )
    op.drop_column(
        "lead_submission",
        "project_summary",
    )
    op.drop_column(
        "lead_submission",
        "company_name",
    )
    op.drop_column(
        "lead_submission",
        "contact_number",
    )
    op.drop_column(
        "lead_submission",
        "full_name",
    )
    op.drop_column(
        "lead_submission",
        "session_id",
    )

    op.drop_constraint(
        None,
        "knowledge_document",
        type_="unique",
    )

    op.drop_index(
        op.f("ix_chat_session_session_token"),
        table_name="chat_session",
    )
    op.drop_column(
        "chat_session",
        "status",
    )
    op.drop_column(
        "chat_session",
        "source_page",
    )
    op.drop_column(
        "chat_session",
        "last_activity_at",
    )
    op.drop_column(
        "chat_session",
        "session_token",
    )

    op.drop_index(
        op.f("ix_chat_message_session_id"),
        table_name="chat_message",
    )
    op.drop_column(
        "chat_message",
        "state",
    )
    op.drop_column(
        "chat_message",
        "intent",
    )

    # ### end Alembic commands ###